Debug work squash for endorlabs-scan.yml

diff --git a/.github/workflows/endorlabs-checks.yml b/.github/workflows/endorlabs-checks.yml
--- a/.github/workflows/endorlabs-checks.yml
+++ b/.github/workflows/endorlabs-checks.yml
@@ -13,8 +13,9 @@ jobs:
       id-token: write
       actions: read
     env:
-      ENDORLABS_TOOL_PATH: "${{ env.GITHUB_WORKSPACE }}/.endorlabs-tools"
       ENDOR_GITHUB_ACTION_TOKEN_ENABLE: "true"
+      ENDOR_NAMESPACE: ${{ secrets.ENDOR_NAMESPACE }}
+      ENDOR_SCAN_PR: "true"
     steps:
       - uses: actions/checkout@v4
 
@@ -22,32 +23,52 @@ jobs:
         id: endorctl-deploy
         shell: bash
         run: |
-          set -eo pipefail
+          echo "::group::Download endorctl"
+          export ENDORLABS_TOOL_PATH="${GITHUB_WORKSPACE}/.endorlabs-tools"
+          mkdir -p "${ENDORLABS_TOOL_PATH}"
+          echo ENDORLABS_TOOL_PATH="${ENDORLABS_TOOL_PATH}" >> $GITHUB_ENV
           curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o "${ENDORLABS_TOOL_PATH}/endorctl"
-          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c && chmod +x "${ENDORLABS_TOOL_PATH}/endorctl"
+          echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  ${ENDORLABS_TOOL_PATH}/endorctl" | sha256sum -c && chmod +x "${ENDORLABS_TOOL_PATH}/endorctl"
           echo ENDORCTL="${ENDORLABS_TOOL_PATH}/endorctl" >> "${GITHUB_ENV}"
+          export ENDORCTL="${ENDORLABS_TOOL_PATH}/endorctl"
+          echo "::endgroup::"
+          if ("${ENDORCTL}" host-check --auth-check-only)
+          then
+            echo "Authorization Check successful"
+          else
+            endor_exit=$?
+            echo "::error::Authorization failure running Endor Labs, code $endor_exit"
+            exit endor_exit
+          fi
 
       - name: secrets check
         id: secrets-scanner
+        env:
+          ENDOR_BYPASS_HOST_CHECK: "true"
         shell: bash
         run: |
           >&2 echo '::group::Secrets scan'
           if ("${ENDORCTL}" scan --secrets --path="${GITHUB_WORKSPACE}" -o json --sarif-file "${ENDORLABS_TOOL_PATH}/endorlabs-results-secrets.sarif" > "${ENDORLABS_TOOL_PATH}/endorlabs-results-secrets.json")
           then
             echo "success"
+            ENDORCTL_EXIT=0
           else
             ENDORCTL_EXIT=$?
             echo "failure with code $ENDORCTL_EXIT"
+          fi
           >&2 echo '::endgroup::'
-          if [[ $ENDORCTL_EXIT == 0 ]]; then
+          echo "results stored in '${ENDORLABS_TOOL_PATH}/endorlabs-results-secrets.sarif' and '${ENDORLABS_TOOL_PATH}/endorlabs-results-secrets.json'"
+
+          if [[ $ENDORCTL_EXIT -eq 0 ]]; then
             exit 0
           elif [[ $ENDORCTL_EXIT -lt 128 ]]; then
-            echo "::error title=endor labs failed with code ${ENDORCTL_EXIT}::Failure during secrets scanning, not policy-related
-            echo "secrets_policies_violated=0"
+            echo "::error title=endor labs failed with code ${ENDORCTL_EXIT}::Failure during secrets scanning, not policy-related, code $ENDORCTL_EXIT"
+            echo "secrets_policies_violated=0" >> $GITHUB_OUTPUT
           else
-            echo "::warning title=secrets policy violated (code ${ENDORCTL_EXIT})::Policy violations found during secrets scanning!"
-            echo "secrets_policies_violated=1"
+            echo "::warning title=secrets policy violated with code ${ENDORCTL_EXIT}::Policy violations found during secrets scanning!"
+            echo "secrets_policies_violated=1" >> $GITHUB_OUTPUT
           fi
+
           echo "endorctl_exit_code=$ENDORCTL_EXIT" >> $GITHUB_OUTPUT
           exit $ENDORCTL_EXIT
 
